-- Function to handle the repeated invocation
local function invokeLuck()
    while true do
        -- Script generated by SimpleSpy - credits to exx#9394
        game:GetService("ReplicatedStorage").Claim:FireServer()
        wait() -- Prevents the loop from running too quickly
    end
end

-- Launch 20 coroutines
for i = 1, 5000 do
    coroutine.wrap(invokeLuck)()
end
