while true do 

    -- Script generated by SimpleSpy - credits to exx#9394
    
    local args = {
        [1] = "pull",
        [2] = "green"
    }
    
    game:GetService("ReplicatedStorage").MinigameEvents.TOWevent:FireServer(unpack(args))
    
    
    wait()
    end