-- -- Script generated by SimpleSpy - credits to exx#9394

-- local args = {
--     [1] = game:GetService("Players").vibeswithwillie,
--     [2] = 0
-- }

-- game:GetService("ReplicatedStorage").TradeSystem.Remotes.LocalPlayerChangeGems:FireServer(unpack(args))

-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = game:GetService("Players").bossjey04,
    [2] = 3,
    [3] = {},
    [4] = 0,
    [5] = {}
}

game:GetService("ReplicatedStorage").TradeSystem.Remotes.LocalPlayerChangeStatus:FireServer(unpack(args))
